title: My Blog Title Here
author: Dan
email: danphan@myspace.com
description: > # this means to ignore newlines until "baseurl:"
  The coolest blog ever.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  danphan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
